config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :drivers, controllers:{
    sessions: 'drivers/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
  resources :suppliers
  resources :transportings
  resources :drivings do
    collection do
      post :unlink
    end
  end
  resources :admins
  resources :users
  resources :vehicles do
    collection do
      post :in_route
      post :exit_route
    end
  end
  resources :drivers do
    collection do
      get :orders
      post :in_route
      post :exit_route
    end
  end
  resources :orders do
    collection do
      post :import
      post :mark_as_delivered
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "main#index"

  get '/rastreio/:codigo_rastreio', to: 'orders#show_by_codigo_rastreio'

  post '/mark_as_delivered/:id', to:'orders#mark_as_delivered'

  get '/unlink/:id', to:'drivings#unlink'

  get '/driver/:id/orders', to:'drivers#orders'

  get '/driver/:id/orders_history', to:'drivers#orders_history'

  get '/driver/:id/vehicles_history', to:'drivers#vehicles_history'

  get '/driver/profile', to:'drivers#profile'

  get '/order/import', to:'orders#csv_form'

end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :driving
    has_many :vehicles, through: :driving

    validates :nome, presence: {message: "Campo Obrigatório"}
    validates :matricula, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:12, message: "Precisa ter Exatamente 12 dígitos"}, numericality: {only_integer: true, message:"Apenas números são permitidos"}
    validates :endereco, presence: {message: "Campo Obrigatório"}
    validates :telefone, presence: {message: "Campo Obrigatório"}

    def self.ransackable_attributes(auth_object = nil)
      ["nome","matricula","endereco","telefone","situacao"]
  end
  def self.ransackable_associations(auth_object = nil)
      [ "drivings", "vehicles"]
  end
end

app/models/driving.rb
class Driving < ApplicationRecord
  belongs_to :driver
  belongs_to :vehicle
end

app/models/order.rb
class Order < ApplicationRecord
    after_update :order_notification

    def self.ransackable_attributes(auth_object = nil)
        ["codigo_rastreio", "created_at", "danfe", "data_fornecimento", "endereco_entrega", "id", "nfe", "status_pedido", "supplier_id", "updated_at", "email"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["supplier", "transporting", "vehicles"]
    end
    
    belongs_to :supplier
    has_many :transporting
    has_many :vehicles, through: :transporting

    validates :danfe, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:44, message: "Precisa ter Exatamente 44 dígitos"}, numericality: {only_integer: true, message:"Apenas números são permitidos"} 
    validates :nfe, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:9, message: "Precisa ter Exatamente 9 dígitos"}, numericality: {only_integer: true, message:"Apenas números são permitidos"}
    validates :codigo_rastreio, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:11, message: "Precisa ter Exatamente 11 dígitos"}, numericality: {only_integer: true, message:"Apenas números são permitidos"}
    validates :endereco_entrega, presence: {message: "Campo Obrigatório"} 
    validates :email, presence: {message: "Campo Obrigatório"} 
    
    private 
    
    def order_notification
        EmailJob.perform_async(id)
    end
    
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :orders

    validates :nome, presence: {message: "Campo Obrigatório"} 

    def self.ransackable_attributes(auth_object = nil)
        ["nome"]
    end
    def self.ransackable_associations(auth_object = nil)
        []
    end
end

app/models/transporting.rb
class Transporting < ApplicationRecord
  belongs_to :order
  belongs_to :vehicle

  validates :origem, presence: {message: "Campo Obrigatório"}
  validates :destino, presence: {message: "Campo Obrigatório"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
  ["nome", "matricula", "email"]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    has_many :transporting
    has_many :orders, through: :transporting

    has_many :driving
    has_many :drivers, through: :driving

    validates :modelo, presence: {message: "Campo Obrigatório"}
    validates :placa, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:7, message: "Precisa ter Exatamente 7 dígitos"}
    
    def self.ransackable_attributes(auth_object = nil)
        ["placa", "modelo", "situacao"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["driving", "transporting", "orders"]
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy, :create]

  # GET /users or /users.json
  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy(@q.result(distinct: true), limit: 10)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:nome, :matricula, :email)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/drivings_helper.rb
module DrivingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    def apenasData(tempo)
        ""+tempo.strftime('%d/%m/%Y')
    end
    def dataTempo(tempo)
        ""+tempo.strftime('%d/%m/%Y - %H:%M:%S')
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/transportings_helper.rb
module TransportingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong>Login:</strong>
    <%= admin.login %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= admin.senha %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
  
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <%= render admin %>
    <p>
      <%= link_to "Show this admin", admin %>
    </p>
  <% end %>
</div>

<%= link_to "New admin", new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<div class="d-flex">
  <!-- Sidebar -->
  <div class="sidebar bg-body-tertiary p-3" style="min-width: 200px;">
    <div class="sidebar-header d-flex align-items-center mb-3">
      <img src="https://i.im.ge/2024/09/13/fzsYXM.logo.jpeg" alt="Logo" class="me-2 sidebar-logo rounded-circle">
      <span class="fs-4">Hermes</span>
    </div>
    <ul class="nav flex-column">
      <%if user_signed_in?%>
        <li class="nav-item">
          <a class="nav-link  d-flex align-items-center" href="/">
            <i class="bi bi-house-door me-2"></i>Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link  d-flex align-items-center" href="/orders">
            <i class="bi bi-bag me-2"></i>Pedidos
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center" href="/drivers">
            <i class="bi bi-person-badge me-2"></i>Motoristas
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center" href="/vehicles">
            <i class="bi bi-truck me-2"></i>Veículos
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center" href="/users">
            <i class="bi bi-people me-2"></i>Usuários
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center" href="/suppliers">
            <i class="bi bi-cart me-2"></i>Fornecedores
          </a>
        </li>
        <li class="nav-item">
            <%= button_to destroy_user_session_path, method: :delete, class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-box-arrow-left me-2"></i>Sair
            <%end%>
        </li>
      <%elsif driver_signed_in?%>
        <li class="nav-item">
          <a class="nav-link  d-flex align-items-center" href="/">
            <i class="bi bi-house-door me-2"></i>Home
          </a>
        </li>
        <li class="nav-item">
          <%= link_to url_for(controller: :drivers, action: :profile), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-person-badge me-2"></i>Perfil
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to url_for(controller: :drivers, action: :orders, id: current_driver.id), class: "nav-link d-flex align-items-center" do%>
                <i class="bi bi-bag me-2"></i>Pedidos para Entregar
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to url_for(controller: :drivers, action: :orders_history, id: current_driver.id), class: "nav-link d-flex align-items-center" do%>
                <i class="bi bi-truck me-2"></i>Histórico de Pedidos
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to url_for(controller: :drivers, action: :vehicles_history, id: current_driver.id), class: "nav-link d-flex align-items-center" do%>
                <i class="bi bi-truck me-2"></i>Histórico de Veículos
          <%end%>
        </li>
        <li class="nav-item">
            <%= button_to destroy_driver_session_path, method: :delete, class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-box-arrow-left me-2"></i>Sair
            <%end%>
        </li>
      <%else%>
        <li class="nav-item">
            <%= link_to new_user_session_path(), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-box-arrow-in-right me-2"></i>Login de Usuário
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to new_driver_session_path(), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-box-arrow-in-right me-2"></i>Login de Motorista
            <%end%>
        </li>
        <%end%>
    </ul>
  </div>
  <!-- Main content 
  <div class="flex-grow-1 p-4 bg-white" >
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2>Bem vindo ao Hermes 👋</h2>
      <div class="d-flex align-items-center">
      <img src="https://images.unsplash.com/photo-1664575600850-c4b712e6e2bf?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Profile" class="profile" style="width: 40px;">
        <div class="me-3">
          <p>Alesia Karpova</p>
          <span class="badge bg-secondary">Administrador</span>
        </div>
      </div>
    </div>    
  </div>
  -->
</div>

app/views/layouts/_toast.html.erb
<% flash.each do |key, value| %>
  <div class="toast_class">
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HermesManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

 



  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'sidebar', media: 'all' %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'index', media: 'all' %> 

   

  <body>
    <%= turbo_frame_tag "modal" %>
    <%= turbo_frame_tag "toast"%>
    <%= yield %>
  </body>
</html>