config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :drivers, controllers:{
    sessions: 'drivers/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
  resources :suppliers
  resources :transportings
  resources :drivings do
    collection do
      post :unlink
    end
  end
  resources :admins
  resources :users
  resources :vehicles do
    collection do
      post :in_route
      post :exit_route
    end
  end
  resources :drivers do
    collection do
      get :orders
      post :in_route
      post :exit_route
    end
  end
  resources :orders do
    collection do
      post :import
      post :mark_as_delivered
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "main#index"

  get '/rastreio/:codigo_rastreio', to: 'orders#show_by_codigo_rastreio'

  post '/mark_as_delivered/:id', to:'orders#mark_as_delivered'

  get '/unlink/:id', to:'drivings#unlink'

  get '/driver/:id/orders', to:'drivers#orders'

  get '/driver/:id/orders_history', to:'drivers#orders_history'

  get '/driver/:id/vehicles_history', to:'drivers#vehicles_history'

  get '/driver/profile', to:'drivers#profile'

  get '/order/import', to:'orders#csv_form'

end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :driving
    has_many :vehicles, through: :driving

    validates :nome, presence: {message: "Campo Obrigatório"}
    validates :matricula, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:12, message: "Precisa ter Exatamente 12 dígitos"}, numericality: {only_integer: true, message:"Apenas números são permitidos"}
    validates :endereco, presence: {message: "Campo Obrigatório"}
    validates :telefone, presence: {message: "Campo Obrigatório"}

    def self.ransackable_attributes(auth_object = nil)
      ["nome","matricula","endereco","telefone","situacao"]
  end
  def self.ransackable_associations(auth_object = nil)
      [ "drivings", "vehicles"]
  end
end

app/controllers/drivers/confirmations_controller.rb
# frozen_string_literal: true

class Drivers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/drivers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Drivers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/drivers/passwords_controller.rb
# frozen_string_literal: true

class Drivers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/drivers/registrations_controller.rb
# frozen_string_literal: true

class Drivers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/drivers/sessions_controller.rb
# frozen_string_literal: true

class Drivers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/drivers/unlocks_controller.rb
# frozen_string_literal: true

class Drivers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy, :create]
  before_action :authenticate_driver!, only: [:profile, :orders,:orders_history,:vehicles_history]

  # GET /drivers or /drivers.json
  def index
    @q = Driver.ransack(params[:q])
    @pagy, @drivers = pagy(@q.result.includes(:vehicles), limit: 10)
  end

  # GET /drivers/1 or /drivers/1.json
  def show
    @drivings = Driving.where(driver_id: @driver.id)
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        flash.now[:notice] = "Motorista Criado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast"),
            turbo_stream.update("modal", partial: "layouts/empty")
          ]
        end
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully created." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        flash.now[:notice] = "Motorista Editado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast"),
            turbo_stream.update("modal", partial: "layouts/empty")
          ]
        end
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully updated." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy!

    respond_to do |format|
      flash.now[:notice] = "Motorista Deletado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast"),
          ]
        end
      format.html { redirect_to drivers_url, notice: "Driver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Paginas do Motorista

  # GET /driver/1/profile
  def profile
    @driver = current_driver
  end

  # GET /driver/1/orders
  def orders
    @last_orders = []
    if @driving = Driving.where(driver_id: current_driver.id).last
      vehicle_id = @driving.vehicle.id
      @transportings = Transporting.where(vehicle_id: vehicle_id)
      for transporting in @transportings
        if transporting.order.transporting.last.vehicle_id == vehicle_id && transporting.order.status_pedido == "A CAMINHO"
          @last_orders.push(transporting.order)
        end
      end
    end
  end

  #POST
  def in_route
    @driving = Driving.where(driver_id: params[:id]).last
    @driver = @driving.driver
    @vehicle = @driving.vehicle
    @driver.update(situacao: "EM ROTA")
    @vehicle.update(situacao: "EM ROTA")
    if user_signed_in?
      redirect_to drivers_path
    elsif driver_signed_in?
      redirect_to orders_drivers_path
    end  
  end

  #POST
  def exit_route
    @driving = Driving.where(driver_id: params[:id]).last
    @driver = @driving.driver
    @vehicle = @driving.vehicle
    @driver.update(situacao: "ATIVO")
    @vehicle.update(situacao: "ATIVO")
    if user_signed_in?
      redirect_to drivers_path
    elsif driver_signed_in?
      redirect_to orders_drivers_path
    end  
  end

  # GET /driver/1/orders_history
  def orders_history
    @transportings = []
    if @driving = Driving.where(driver_id: current_driver.id).last 
      @transportings = Transporting.where(vehicle_id: @driving.vehicle.id) 
    end
  end

  # GET /driver/1/vehicles_history
  def vehicles_history
    @drivings = Driving.where(driver_id: current_driver.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:nome, :matricula, :endereco, :telefone, :email, :password)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_driver.html.erb
<div id="<%= dom_id driver %>">
  <p>
    <strong>Nome:</strong>
    <%= driver.nome %>
  </p>

  <p>
    <strong>Matricula:</strong>
    <%= driver.matricula %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= driver.endereco %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= driver.telefone %>
  </p>

  <p>
    <strong>Login:</strong>
    <%= driver.login %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= driver.senha %>
  </p>

</div>

app/views/drivers/_driver_home.html.erb
<div class="main-content flex-grow-1 p-3 custom-home-style">
  <div>
    <div class="text-center mb-4">
      <h1 class="custom-title display-4 text-welcome">Bem-vindo, <%= current_driver.nome %>!</h1>
      <p class="custom-lead lead text-muted">Matrícula: <%= current_driver.matricula %></p>
      <h3>Acesse o menu lateral para realizar suas atividades</h3>
    </div>

    <hr class="my-4">
  </div>

<div class="image-container mt-4" style="width: 100%; height: 68vh;">
<img src="https://brazilgreece.com/wp-content/uploads/2024/02/hermes-deus-grego.webp" alt="House Image" style="width: 100%; height: 100%; object-fit: cover;">
</div>
</div>

app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
  <% if driver.errors.any? %>
    <div style="color: red">
      <ul>
        <% driver.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, class: "form-label" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div>
    <%= form.label :matricula, class: "form-label" %>
    <%= form.text_field :matricula, class: "form-control" %>
  </div>

  <div>
    <%= form.label :endereco, class: "form-label" %>
    <%= form.text_field :endereco, class: "form-control" %>
  </div>

  <div>
    <%= form.label :telefone, class: "form-label" %>
    <%= form.text_field :telefone, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, class: "form-label"%>
    <%= form.email_field :email, class: "form-control"%>
  </div>

  <div>
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div>
    <br>
    <%= form.submit "Confirmar", class: "btn btn-success"%>
    <%= link_to "Cancelar", "#", data:{
          controller: "modals",
          action: "modals#close"
        }, class: "cancel-button btn btn-danger" %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<%= turbo_frame_tag  "modal" do%>
  <div class="popup">
    <div style="margin-left:1rem">
      <h1>Editar Motorista</h1>
      <%= render "form", driver: @driver %>
    </div>
  </div>
<%end%>

app/views/drivers/index.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="titulo">Motoristas</h2>
    <%= link_to "Adicionar Motorista", new_driver_path, data:{turbo_frame: "modal"}, class: "btn btn-adicionar-pedido" %>
  </div>

  <div class="container-fluid">
  <%= search_form_for @q do |f| %>
    <div class="d-flex">
      <%= f.search_field :nome_or_matricula_or_endereco_or_telefone_or_situacao_cont, placeholder:"Pesquisar" %>
      <button class="btn btn-sm btn-outline-info"><i class="bi bi-search"></i></button>
    </div>
  <% end %>
    <div class="table-responsive shadow-sm p-4 mb-5 bg-white rounded">
      <table class="table table-hover table-borderless align-middle">
        <thead class="table-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col"><%= sort_link(@q, :nome, 'Nome') %></th>
            <th scope="col"><%= sort_link(@q, :matricula, 'Matricula') %></th>
            <th scope="col"><%= sort_link(@q, :endereco, 'Endereço') %></th>
            <th scope="col"><%= sort_link(@q, :telefone, 'Telefone') %></th>
            <th scope="col"><%= sort_link(@q, :situacao, 'Situacao') %></th>
            <th scope="col" class="text-center">Opções</th>
          </tr>
        </thead>
        <tbody>
          <% @drivers.each_with_index do |driver, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= driver.nome %></td>
              <td><%= driver.matricula %></td>
              <td><%= driver.endereco %></td>
              <td><%= driver.telefone %></td>
              <td>
                <% badge_class = case driver.situacao
                  when 'ATIVO' then 'badge-ativo'
                  when 'INATIVO' then 'badge-inativo'
                  else 'badge-defaut'
                end %>
                <span class="badge rounded-pill <%= badge_class %>">
                  <%= driver.situacao %>
                </span>

              </td>
              <td class="text-center">
                <div class="btn-group">
                  <%= link_to edit_driver_path(driver), data:{turbo_frame: "modal"}, class: "btn btn-sm btn-outline-info", title: "Editar" do %>
                    <i class="bi bi-pencil"></i>
                  <% end %>
                  <%= link_to driver_path(driver), class: "btn btn-sm btn-outline-info", title: "Detalhar" do %>
                    <i class="bi bi-search"></i>
                  <% end %>
                  <%= button_to driver, method: :delete, class: "btn btn-sm btn-outline-danger", data: { "turbo-method": :delete, 'turbo-confirm': "Você tem Certeza?" }, title: "Deletar" do %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                  <% if driver.situacao == "ATIVO"%>
                    <%= form_with(url: unlink_drivings_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: driver.id %>
                      <%= form.hidden_field :is_driver, value: true%>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-heartbreak"></i></button>
                    <% end %>
                    <%= form_with(url: in_route_drivers_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: driver.id %>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-box-arrow-in-right"></i></button>
                    <% end %>
                  <% elsif driver.situacao == "EM ROTA"%>
                    <%= form_with(url: exit_route_drivers_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: driver.id %>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-box-arrow-right"></i></button>
                    <% end %>
                  <% else %>
                    <%= link_to url_for(controller: :drivings, action: :new, id: driver.id, is_driver: true), class: "btn btn-sm btn-outline-info", data:{turbo_frame: "modal"}, title:"Vincular Veículo" do%>
                      <i class="bi bi-link"></i>
                    <% end%>
                  <% end%>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- Paginação -->
    <div class="d-flex justify-content-center pag">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/drivers/new.html.erb
<%= turbo_frame_tag  "modal" do%>
  <div class="popup">
      <h2>Adicionar Motorista</h2>
      <%= render "form", driver: @driver %>
  </div>
<%end%>

app/views/drivers/orders.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="titulo">Entregas Para Realizar</h2>
  </div>

<div class="container-fluid">
    <% if current_driver.situacao == "ATIVO"%>
      <%= form_with(url: in_route_drivers_path, method: :post) do |form| %>
        <%= form.hidden_field :id, value: current_driver.id %>
        <button class="btn btn-sm btn-info btn-outline-info">Iniciar Rota</button>
      <% end %>
    <% elsif current_driver.situacao == "EM ROTA" && @last_orders.length() == 0%>
      <%= form_with(url: exit_route_drivers_path, method: :post) do |form| %>
        <%= form.hidden_field :id, value: current_driver.id %>
        <button class="btn btn-sm btn-info btn-outline-info">Finalizar Rota</i></button>
      <% end %>
    <% end%>
    <div class="table-responsive shadow-sm p-4 mb-5 bg-white rounded">
      <table class="table table-hover table-borderless align-middle orders-table">
        <thead class="table-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Codigo de Rastreio</th>
            <th scope="col">Endereço Origem</th>
            <th scope="col">Endereço Destino</th>
            <th scope="col">Status</th>
            <th scope="col">Data de Despacho</th>
            <%if current_driver.situacao == "EM ROTA"%>
              <th scope="col" class="text-center">Opções</th>
            <%end%>
          </tr>
        </thead>
        <tbody>
          <% @last_orders.each_with_index do |order, index| %>
            <%if order.status_pedido == "A CAMINHO"%>
                <tr>
                <th scope="row"><%= index+1 %></th>
                <td><%= order.codigo_rastreio %></td>
                <td><%= order.transporting.last.origem %></td>
                <td><%= order.transporting.last.destino %></td>
                <td>
                    <% badge_class = case order.status_pedido
                    when 'ENTREGUE' then 'badge-recebido'
                    when 'PENDENTE' then 'badge-pendente'
                    when 'EM ESPERA' then 'badge-espera'
                    else 'badge-defaut'
                    end %>
                    <span class="badge rounded-pill <%= badge_class %>">
                    <%= order.status_pedido %>
                    </span>
                </td>
                <td><%= apenasData(order.transporting.last.data_despache) %></td>
                <%if current_driver.situacao == "EM ROTA"%>
                  <td class="text-center">
                    <div class="btn-group">
                        <% if order.status_pedido == "A CAMINHO" %>
                          <%= form_with(url: mark_as_delivered_orders_path, method: :post) do |form| %>
                            <%= form.hidden_field :id, value: order.id %>
                            <button class="btn btn-sm btn-outline-info"><i class="bi bi-check-lg"></i></button>
                          <% end %>
                        <% end %>
                    </div>
                  </td>
                <%end%>
                </tr>
            <%end%>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/drivers/orders_history.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="titulo">Histórico de Entregas</h2>
  </div>

  <div class="container-fluid">
    <div class="table-responsive shadow-sm p-4 mb-5 bg-white rounded">
      <table class="table table-hover table-borderless align-middle orders-table">
        <thead class="table-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Codigo de Rastreio</th>
            <th scope="col">Endereço Origem</th>
            <th scope="col">Endereço Destino</th>
            <th scope="col">Status</th>
            <th scope="col">Data de Despacho</th>
          </tr>
        </thead>
        <tbody>
          <% @transportings.each_with_index do |transporting, index| %>
            <tr>
              <th scope="row"><%= index+1 %></th>
              <td><%= transporting.order.codigo_rastreio %></td>
              <td><%= transporting.origem %></td>
              <td><%= transporting.destino %></td>
              <td>
                <% badge_class = case transporting.order.status_pedido
                  when 'ENTREGUE' then 'badge-recebido'
                  when 'PENDENTE' then 'badge-pendente'
                  when 'EM ESPERA' then 'badge-espera'
                  else 'badge-defaut'
                end %>
                <span class="badge rounded-pill <%= badge_class %>">
                  <%= transporting.order.status_pedido %>
                </span>
              </td>
              <td><%= apenasData(transporting.data_despache) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/drivers/profile.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="titulo">Perfil</h2>
  </div>
  <div class="container-fluid">
  <div class="card p-4 shadow-sm mb-4">
    <div class="row">
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Nome</h4>
        <p class="info-conteudo"><%= @driver.nome%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Matrícula</h4>
        <p class="info-conteudo"><%=@driver.matricula%></p>
      </div>
      
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Endereço</h4>
        <p class="info-conteudo"><%=@driver.endereco%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Telefone</h4>
        <p class="info-conteudo"><%=@driver.telefone%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Situacao</h4>
        <p class="info-conteudo"><%=@driver.situacao%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Email</h4>
        <p class="info-conteudo"><%=@driver.email%></p>
      </div>
    </div>
  </div>
    <div class="container text-center">
      <div class="row">
        <div class="col">
          <%= link_to driver_path(current_driver.id), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-person-badge me-2"></i>Histórico de Pedidos
          <%end%>
        </div>
        <div class="col">
          <%= link_to driver_path(current_driver.id), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-person-badge me-2"></i>Histórico de Veículos
          <%end%>
        </div>
      </div>
    </div>
</div>
</div>

app/views/drivers/show.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <%if driver_signed_in?%>
      <h2 class="titulo">Perfil</h2>
    <%elsif user_signed_in?%>
      <h2 class="titulo">Motorista -  <%= @driver.nome%></h2>
    <% end %>
  </div>
  <div class="container-fluid">
  <div class="card p-4 shadow-sm mb-4">
    <div class="row">
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Nome</h4>
        <p class="info-conteudo"><%= @driver.nome%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Matrícula</h4>
        <p class="info-conteudo"><%=@driver.matricula%></p>
      </div>
      
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Endereço</h4>
        <p class="info-conteudo"><%=@driver.endereco%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Telefone</h4>
        <p class="info-conteudo"><%=@driver.telefone%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Situacao</h4>
        <p class="info-conteudo"><%=@driver.situacao%></p>
      </div>
      <div class="col-md-6 mb-3">
        <h4  class="info-titulo">Email</h4>
        <p class="info-conteudo"><%=@driver.email%></p>
      </div>
    </div>
  </div>
  <%if driver_signed_in?%>
    <div class="container text-center">
      <div class="row">
        <div class="col">
          <%= link_to driver_path(current_driver.id), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-person-badge me-2"></i>Histórico de Pedidos
          <%end%>
        </div>
        <div class="col">
          <%= link_to driver_path(current_driver.id), class: "nav-link d-flex align-items-center" do%>
              <i class="bi bi-person-badge me-2"></i>Histórico de Veículos
          <%end%>
        </div>
      </div>
    </div>
  <%elsif user_signed_in?%>
    <div class="card p-4 shadow-sm mt-5">
      <h3 class="titulo">Histórico de Veículos do Motorista</h3>
      <% @drivings.each do |driving|%>
          <div>
            <%= render driving%>
            <hr>
          </div>
        <%end%>
    </div>
  <% end %>
</div>
</div>

app/views/drivers/vehicles_history.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="main-content flex-grow-1 p-3">
    <h1>Histórico de Veículos</h1>
    <hr>
    <div class="card p-4 shadow-sm mt-5">
      <h3 class="titulo">Histórico de Veículos do Motorista</h3>
      <% @drivings.each do |driving|%>
          <div>
            <%= render driving%>
            <hr>
          </div>
        <%end%>
    </div>
</div>