config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do 
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :drivers, controllers:{
    sessions: 'drivers/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
  resources :suppliers
  resources :transportings
  resources :drivings do
    collection do
      post :unlink
    end
  end
  resources :admins
  resources :users
  resources :vehicles do
    collection do
      post :in_route
      post :exit_route
    end
  end
  resources :drivers do
    collection do
      get :orders
      post :in_route
      post :exit_route
    end
  end
  resources :orders do
    collection do
      post :import
      post :mark_as_delivered
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "main#index"

  get '/rastreio/:codigo_rastreio', to: 'orders#show_by_codigo_rastreio'

  post '/mark_as_delivered/:id', to:'orders#mark_as_delivered'

  get '/unlink/:id', to:'drivings#unlink'

  get '/driver/:id/orders', to:'drivers#orders'

  get '/driver/:id/orders_history', to:'drivers#orders_history'

  get '/driver/:id/vehicles_history', to:'drivers#vehicles_history'

  get '/driver/profile', to:'drivers#profile'

  get '/order/import', to:'orders#csv_form'

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    has_many :transporting
    has_many :orders, through: :transporting

    has_many :driving
    has_many :drivers, through: :driving

    validates :modelo, presence: {message: "Campo Obrigatório"}
    validates :placa, presence: {message: "Campo Obrigatório"}, uniqueness: {message: "Já Foi Utilizado"}, length: {is:7, message: "Precisa ter Exatamente 7 dígitos"}
    
    def self.ransackable_attributes(auth_object = nil)
        ["placa", "modelo", "situacao"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["driving", "transporting", "orders"]
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :update, :destroy, :create]

  # GET /vehicles or /vehicles.json
  def index
    @q = Vehicle.ransack(params[:q])
    @pagy, @vehicles = pagy(@q.result.includes(:driving), limit: 10)
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
    @transportings = Transporting.where(vehicle_id: @vehicle.id)
    @drivings = Driving.where(vehicle_id: @vehicle.id)
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  def unlink
  end

  def in_route
    @driving = Driving.where(vehicle_id: params[:id]).last
    @driver = @driving.driver
    @vehicle = @driving.vehicle
    @driver.update(situacao: "EM ROTA")
    @vehicle.update(situacao: "EM ROTA")
    redirect_to vehicles_path
  end

  def exit_route
    @driving = Driving.where(vehicle_id: params[:id]).last
    @driver = @driving.driver
    @vehicle = @driving.vehicle
    @driver.update(situacao: "ATIVO")
    @vehicle.update(situacao: "ATIVO")
    redirect_to vehicles_path
  end
  

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        flash.now[:notice] = "Veículo Criado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast"),
            turbo_stream.update("modal", partial: "layouts/empty")
          ]
        end
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        flash.now[:notice] = "Veículo Editado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast"),
            turbo_stream.update("modal", partial: "layouts/empty")
          ]
        end
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy!

    respond_to do |format|
      flash.now[:notice] = "Veículo Deletado com Sucesso"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("toast", partial:"layouts/toast")
          ]
        end
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:placa, :modelo)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :placa, class: "form-label" %>
    <%= form.text_field :placa, class: "form-control" %>
  </div>

  <div>
    <%= form.label :modelo, class: "form-label" %>
    <%= form.text_field :modelo, class: "form-control" %>
  </div>

  <div>
    <br>
    <%= form.submit "Confirmar", class: "btn btn-success"%>
    <%= link_to "Cancelar", "#", data:{
          controller: "modals",
          action: "modals#close"
        }, class: "cancel-button btn btn-danger" %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <p>
    <strong>Placa:</strong>
    <%= vehicle.placa %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= vehicle.modelo %>
  </p>

</div>

app/views/vehicles/edit.html.erb
<%= turbo_frame_tag  "modal" do%>
  <div class="popup">
    <div style="margin-left:1rem">
      <h1>Editar Veículo</h1>
      <%= render "form", vehicle: @vehicle %>
    </div>
  </div>
<%end%>

app/views/vehicles/index.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="titulo">Veículos</h2>
    <%= link_to "Adicionar Veículo", new_vehicle_path, data:{turbo_frame: "modal"}, class: "btn btn-adicionar-pedido" %>
  </div>

  <div class="container-fluid">
    <%= search_form_for @q do |f| %>
      <div class="d-flex">
        <%= f.search_field :placa_or_modelo_or_situacao_cont, placeholder:"Pesquisar" %>
        <button class="btn btn-sm btn-outline-info"><i class="bi bi-search"></i></button>
      </div>
    <% end %>
    <div class="table-responsive shadow-sm p-4 mb-5 bg-white rounded">
      <table class="table table-hover table-borderless align-middle">
        <thead class="table-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col"><%= sort_link(@q, :placa, 'Placa') %></th>
            <th scope="col"><%= sort_link(@q, :modelo, 'Modelo') %></th>
            <th scope="col"><%= sort_link(@q, :situacao, 'Situação') %></th>
            <th scope="col" class="text-center">Opções</th>
          </tr>
        </thead>
        <tbody>
          <% @vehicles.each_with_index do |vehicle, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= vehicle.placa %></td>
              <td><%= vehicle.modelo %></td>
              <td>
                <% badge_class = case vehicle.situacao
                  when 'ATIVO' then 'badge-ativo'
                  when 'INATIVO' then 'badge-inativo'
                  else 'badge-defaut'
                end %>
                <span class="badge rounded-pill <%= badge_class %>">
                  <%=vehicle.situacao%>
                </span>
              </th>
              <td class="text-center">
                <div class="btn-group">
                  <%= link_to edit_vehicle_path(vehicle), class: "btn btn-sm btn-outline-info", title: "Editar", data:{turbo_frame: "modal"} do %>
                    <i class="bi bi-pencil"></i>
                  <% end %>
                  <%= link_to vehicle_path(vehicle), class: "btn btn-sm btn-outline-info", title: "Detalhar" do %>
                    <i class="bi bi-search"></i>
                  <% end %>
                  <%= button_to vehicle, method: :delete, class: "btn btn-sm btn-outline-danger", data: { "turbo-method": :delete, 'turbo-confirm': "Você tem Certeza?" }, title: "Deletar" do %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                  <% if vehicle.situacao == "ATIVO"%>
                    <%= form_with(url: unlink_drivings_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: vehicle.id %>
                      <%= form.hidden_field :is_vehicle, value: true%>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-heartbreak"></i></button>
                    <% end %>
                    <%= form_with(url: in_route_vehicles_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: vehicle.id %>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-box-arrow-in-right"></i></button>
                    <% end %>
                  <% elsif vehicle.situacao == "EM ROTA"%>
                    <%= form_with(url: exit_route_vehicles_path, method: :post) do |form| %>
                      <%= form.hidden_field :id, value: vehicle.id %>
                      <button class="btn btn-sm btn-outline-info"><i class="bi bi-box-arrow-right"></i></button>
                    <% end %>
                  <% else %>
                    <%= link_to url_for(controller: :drivings, action: :new, id: vehicle.id, is_vehicle: true), class: "btn btn-sm btn-outline-info", data:{turbo_frame: "modal"} do%>
                      <i class="bi bi-link"></i>
                    <%end%>
                  <% end%>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- Paginação -->
    <div class="d-flex justify-content-center pag">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<%= turbo_frame_tag  "modal" do%>
  <div class="popup">
      <h2>Adicionar Veículo</h2>
      <%= render "form", vehicle: @vehicle %>
  </div>
<%end%>

app/views/vehicles/show.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="main-content flex-grow-1 p-3">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="titulo">Veículo <%= @vehicle.placa%></h2>
  </div>
  <div class="container-fluid">
    <div class="card p-4 shadow-sm mb-4">
      <div class="row">
        <div class="col-md-6 mb-3">
          <h4 class="info-titulo">Placa</h4>
          <p class="info-conteudo"><%= @vehicle.placa %></p>
        </div>
        <div class="col-md-6 mb-3">
          <h4 class="info-titulo">Modelo</h4>
          <p class="info-conteudo"><%= @vehicle.modelo %></p>
        </div>
        <div class="col-md-6 mb-3">
          <h4 class="info-titulo">Situação</h4>
          <p class="info-conteudo"><%= @vehicle.situacao %></p>
        </div>
      </div>
    </div>
    <div class="card p-4 shadow-sm mt-5">
      <h3>Histórico de Transportes do Veículo</h3>
      <% @transportings.each do |transporting|%>
        <div>
          <%= render transporting%>
          <hr>
        </div>
      <%end%>
    </div>

    <div class="card p-4 shadow-sm mt-5">
      <h3>Histórico de Motoristas do Veículo</h3>
      <% @drivings.each do |driving|%>
        <div>
          <%= render driving%>
          <hr>
        </div>
      <%end%>
    </div>
  </div>
</div>